# Generated by Django 6.0 on 2025-12-17 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('BUSINESS_CREATED', 'Business Created'), ('BUSINESS_UPDATED', 'Business Updated'), ('BUSINESS_SUSPENDED', 'Business Suspended'), ('BUSINESS_ACTIVATED', 'Business Activated'), ('BUSINESS_DELETED', 'Business Deleted'), ('LICENSE_CREATED', 'License Created'), ('LICENSE_RENEWED', 'License Renewed'), ('LICENSE_EXPIRED', 'License Expired'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DELETED', 'User Deleted'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('SYSTEM_BACKUP', 'System Backup'), ('SYSTEM_UPDATE', 'System Update'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='businesses.business')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Activity',
                'verbose_name_plural': 'System Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success'), ('LICENSE', 'License'), ('PAYMENT', 'Payment'), ('SECURITY', 'Security'), ('BUSINESS', 'Business'), ('USER', 'User')], default='INFO', max_length=20),
        ),
    ]
