# Generated by Django 6.0 on 2025-12-17 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('available_in_demo', models.BooleanField(default=False)),
                ('available_in_basic', models.BooleanField(default=False)),
                ('available_in_pro', models.BooleanField(default=False)),
                ('available_in_enterprise', models.BooleanField(default=True)),
                ('requires_setup', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('icon', models.CharField(default='fa-cog', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('POS', 'POS Features'), ('INVENTORY', 'Inventory Management'), ('REPORTING', 'Reporting & Analytics'), ('STAFF', 'Staff Management'), ('INTEGRATION', 'Integrations'), ('SECURITY', 'Security Features'), ('OTHER', 'Other Features')], default='POS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('DEMO', 'Demo/Trial'), ('BASIC', 'Basic'), ('PRO', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='DEMO', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('max_users', models.IntegerField(default=5)),
                ('max_products', models.IntegerField(default=1000)),
                ('max_branches', models.IntegerField(default=1)),
                ('max_storage_mb', models.IntegerField(default=100)),
                ('payment_method', models.CharField(blank=True, choices=[('MPESA', 'M-PESA'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Bank Transfer'), ('CASH', 'Cash')], max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='businesses.business')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='businesses.business')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_access', to='licenses.feature')),
            ],
            options={
                'verbose_name': 'Business Feature',
                'verbose_name_plural': 'Business Features',
                'unique_together': {('business', 'feature')},
            },
        ),
    ]
